// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ueihqnbzlogdfkyodgob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlaWhxbmJ6bG9nZGZreW9kZ29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjExMDQsImV4cCI6MjA3MDEzNzEwNH0.OH0QFQdWI0YlNRvLRe2udF0by12vRlbgWVaddomtAC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});